import 'package:flutter/material.dart';
import 'package:record/record.dart';
import 'dart:async';

class AudioRecorderWidget extends StatefulWidget {
  final Function(String path) onStop;
  const AudioRecorderWidget({super.key, required this.onStop});

  @override
  State<AudioRecorderWidget> createState() => _AudioRecorderWidgetState();
}

class _AudioRecorderWidgetState extends State<AudioRecorderWidget> {
  late AudioRecorder _recorder;
  bool _isRecording = false;
  int _recordDuration = 0;
  Timer? _timer;

  @override
  void initState() {
    super.initState();
    _recorder = AudioRecorder();
  }

  @override
  void dispose() {
    _timer?.cancel();
    _recorder.dispose();
    super.dispose();
  }

  Future<void> _start() async {
    try {
      if (await _recorder.hasPermission()) {
        const config = RecordConfig(); 
        await _recorder.start(config, path: ''); // Path auto-generated by package
        setState(() {
          _isRecording = true;
          _recordDuration = 0;
        });
        _timer = Timer.periodic(const Duration(seconds: 1), (t) {
          setState(() => _recordDuration++);
        });
      }
    } catch (e) { print(e); }
  }

  Future<void> _stop() async {
    final path = await _recorder.stop();
    _timer?.cancel();
    setState(() => _isRecording = false);
    if (path != null) widget.onStop(path);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        if (_isRecording)
          Text("${_recordDuration}s", style: const TextStyle(color: Colors.red, fontWeight: FontWeight.bold)),
        IconButton(
          iconSize: 48,
          icon: Icon(_isRecording ? Icons.stop_circle : Icons.mic_none, 
                     color: _isRecording ? Colors.red : Colors.blue),
          onPressed: _isRecording ? _stop : _start,
        ),
      ],
    );
  }
}